### PR TITLE
upgrade Go, Runc, Docker and Containerd

### PR DESCRIPTION
**Pull request by flatcar-infra**
In this PR we upgrade Go to upgrade Runc to upgrade Containerd and Docker.

Closes: https://github.com/flatcar/Flatcar/issues/1530
Closes: https://github.com/flatcar/Flatcar/issues/1539
Closes: https://github.com/flatcar/Flatcar/issues/1546

TODO:
- [x] changelog entry (update + CVE)
- [x] check Docker changelog for breaking changes (nothing for containerd, nor runc)
- [x] upstream PR for runc: https://github.com/gentoo/gentoo/pull/38630
- [ ] upstream PR for docker: TBD
- [x] CI w/ SDK on all platforms: : http://localhost:8080/job/container/job/sdk/1756/cldsv/ (except for unrelated issues with cl.tpm.eventlog of amd64/qemu_uefi_secure).

### CODE REVIEW

**Comment by dongsupark** [comment]
CI passed, http://localhost:8080/job/container/job/sdk/1756/cldsv/.

**Comment by chewi** [comment]
I'm a little confused. We've bumped runc and containerd in Gentoo, but not Docker, even though we have it in portage-stable? I don't mind if we need to do it urgently for security, but I feel like we should at least try to get it bumped there first. If we already had a request open, I could get it merged now, but I can't reasonably do that if the maintainer hasn't been given a chance yet.

**Comment by dongsupark** [comment]
> I'm a little confused. We've bumped runc and containerd in Gentoo, but not Docker, even though we have it in portage-stable? I don't mind if we need to do it urgently for security, but I feel like we should at least try to get it bumped there first. If we already had a request open, I could get it merged now, but I can't reasonably do that if the maintainer hasn't been given a chance yet.

Upstream PR for docker 27.2.1 is still to be done.
I can look into that next week.

**Review by chewi — APPROVED** [review]

**Review by krnowak — APPROVED** [review]
Looks alright, but the weekly updates will clobber our new docker ebuilds (unless they will get upstreamed by that time), so we will need to remember to revert the changes when working on the updates next time.

**Comment by krnowak** [comment]
There are some conflicts to resolve, because I merged the weekly updates PR.

**Pull request merged**
