### PR TITLE
app-emulation/actool,acbuild: Remove actool and acbuild

### PR DESCRIPTION
**Pull request by pothos**
Both actool and acbuild upstream are deprecated and probably not in use anymore.
Remove actool from the image and acbuild from the SDK.

Second commit:

Remove ACI image building bits
    
    The ACI OEM container image was used with rkt for GCE. For long time
    this has been migrated to systemd-nspawn and now systemd-sysext.
    Remove the unused build library code.

## Testing done

In the GitHub Action CI and on [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3767/cldsv/).

### CODE REVIEW

**Comment by pothos** [comment]
Hm, that `/update-sdk` comment didn't work…

**Comment by dongsupark** [comment]
> Hm, that `/update-sdk` comment didn't work…

As far as I know, once you add `/update-sdk` in a comment or description, you have to refresh any commit, and push to the PR again, so that CI can pick up the event. Without doing that, CI would still skip building SDK.
What I usually do is: `git commit --amend --no-edit --date=now && git push --force origin <branchname>`

**Comment by pothos** [comment]
The aci file for the GCE OEM wasn't even using this, it was using tar. I guess we can also clean up this a bit: `build_library/oem_aci_util.sh`, `build_oem_aci` and calls from `image_to_vm.sh` and `build_library/vm_image_util.sh` to `oem_aci`

**Review by krnowak — APPROVED** [review]

**Comment by krnowak** [comment]
> The aci file for the GCE OEM wasn't even using this, it was using tar. I guess we can also clean up this a bit: `build_library/oem_aci_util.sh`, `build_oem_aci` and calls from `image_to_vm.sh` and `build_library/vm_image_util.sh` to `oem_aci`

That'd be a nice cleanup. Can be done in follow-up PR if you want to merge this now.

**Comment by pothos** [comment]
Pushed the cleanup, maybe we should also do a jenkins build

**Comment by krnowak** [comment]
> Pushed the cleanup, maybe we should also do a jenkins build

Yes, please.

**Comment by pothos** [comment]
Jenkins VM image building passed.

An unrelated failure in `cl.verity/corruption` only on amd64 is strange, though.

**Comment by pothos** [comment]
> An unrelated failure in `cl.verity/corruption` only on amd64 is strange, though.

Since it passed on GitHub Actions this really seems to unrelated.

**Comment by krnowak** [comment]
> > An unrelated failure in `cl.verity/corruption` only on amd64 is strange, though.
> 
> Since it passed on GitHub Actions this really seems to unrelated.

Alright, let's merge it, then.

**Comment by pothos** [comment]
I wonder if the kola test could be improved to corrupt a bit more and try to flush the cashes again when the first corruption didn't directly trigger the panic.

**Comment by pothos** [comment]
I've tested the case manually and it helps to overwrite 100 MB instead of 10 MB, will file a mantle PR

**Pull request merged**
