### PR TITLE
nvidia-drivers: Improve match for NVIDIA GPUs

### PR DESCRIPTION
**Pull request by jepio**
# nvidia-drivers: Improve match for NVIDIA GPUs
The logic for checking if we need to probe depends on the device showing up with the product type in lspci output, which doesn't hold for all sorts of GPUs. The NVIDIA_PRODUCT_TYPE is used for fetching the drivers and is "tesla" across datacenter GPUs.

Switch to matching on vendor id and device class. The values are the same ones that the nvidia driver binds to.

## How to use

[ describe what reviewers need to do in order to validate this PR ]

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by jepio** [comment]
This addresses #1364

**Comment by jepio** [comment]
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3509/cldsv/

**Review by krnowak — COMMENTED** [review]
I guess that the changes are fine, but I'd like to ask you to bump the revision of the x11-drivers/nvidia-drivers ebuild.

**Review by sayanchowdhury — APPROVED** [review]
LGTM. Agreed with @krnowak thoughts.

**Review by krnowak — APPROVED** [review]

**Pull request merged**
