### PR TITLE
Move docker packages from app-emulation to app-containers

### PR DESCRIPTION
**Pull request by krnowak**
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1920/cldsv

~Blocked on #863.~

Drops some more modifications from docker ebuild.

- [x] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by krnowak** [comment]
Needs https://github.com/flatcar/mantle/pull/438 to be merged first.

**Comment by krnowak** [comment]
CI passed.

**Review by dongsupark — APPROVED** [review]
Nice, thanks.

**Comment by krnowak** [comment]
Meh, I sometimes think we should have a monorepo. That way I would notice it.

**Comment by krnowak** [comment]
See https://github.com/flatcar/flatcar-linux-release-info/pull/25.

**Pull request merged**
