### PR TITLE
app-emulation: Upgrade Docker 20.10.24 to 20.10.25

### PR DESCRIPTION
**Pull request by krnowak**
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1872/cldsv

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [x] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by krnowak** [comment]
`systemd.sysext.custom-docker` failed for 20.10.25, because 20.10.25 binaries are still not available in neither https://download.docker.com/linux/static/stable/x86_64/ nor https://download.docker.com/linux/static/stable/aarch64/

**Comment by dongsupark** [comment]
Ok, let's wait for now. Added `on-hold`.

**Comment by dongsupark** [comment]
As it is outdated, and the missing tarballs will not be available, I would like to suggest closing the PR.

**Comment by krnowak** [comment]
Yeah, updating to 24.x would be a better way forward. Closing then.

**Pull request closed without merging**
