### PR TITLE
Migrate from glibc libcrypt to sys-libs/libxcrypt

### PR DESCRIPTION
**Pull request by krnowak**
This ought to be done long time ago, as the glibc crypt functionality is deprecated since 2.30 or 2.33 or so. The sys-libs/libxcrypt provides the replacement. Glibc crypt stuff is supposed to be dropped in 2.39, so really soon. We are using 2.38 at the moment.

I think I punted the migration because I was getting some dependency loop issues (dev-lang/python -> virtual/crypt -> sys-libs/libxcrypt -> sys-libs/glibc -> dev-lang/python). Let's see how it goes now.

CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1474/cldsv/

- [x] changelog
- [x] image diff

### CODE REVIEW

**Comment by krnowak** [comment]
CI passed.

**Comment by dongsupark** [comment]
Can you please rebase and run Jenkins CI again?
I remember I have seen it already passed, but just to be sure.

**Comment by krnowak** [comment]
Rebased, CI kicked off.

**Review by dongsupark — APPROVED** [review]
Thanks

**Pull request merged**
