### PR TITLE
Mount btrfs fs with rescue= option

### PR DESCRIPTION
**Pull request by jepio**
# Mount btrfs fs with rescue= option

It looks like 'norecovery' is deprecated and has been removed in the v6.8-rc1 kernel. Replace it with 'rescue=nologreplay', which is a replacement implemented since v5.9. The standalone 'nologreplay' option is also deprecated.

Also need to pull in this:
- [x] https://github.com/flatcar/update_engine/pull/40
but thats tied to us updating to v6.8+ which means we still have time.

## How to use

[ describe what reviewers need to do in order to validate this PR ]

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by pothos** [comment]
Thanks

**Comment by ader1990** [comment]
Hello @jepio, I am usually running my dev env on Ubuntu latest version aka 24.04 Noble, and this week the kernel got upgraded from 6.6 to 6.8. Without this patch, `./build_image` fails, thanks for the fix.

**Review by ader1990 — APPROVED** [review]
LGTM. required for Ubuntu 24.04.

**Comment by jepio** [comment]
Thanks; I've added a commit to bump update_engine, will merge after running tests.

**Pull request merged**
