### PR TITLE
Update from python3.10 to python3.11 in profile

### PR DESCRIPTION
**Pull request by krishjainx**
# Bump from python3.10 to python3.11 in profile

We switch to newer version of python mostly because older versions get obsoleted in Gentoo. 3.10 is not yet obsolete, but eventually we will want to switch to python 3.11.

## How to use

Already spoke with @krnowak

### CODE REVIEW

**Comment by krnowak** [comment]
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/898/cldsv

**Comment by krnowak** [comment]
Build failed because python 3.11.3 requires app-crypt/libb2 which isn't available. Could you pull that in into portage-stable please? Thanks!

**Comment by krnowak** [comment]
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/902/cldsv

**Comment by jepio** [comment]
```
12:46:36  emerge: there are no ebuilds to satisfy "dev-lang/python-exec[python_targets_python3_10(-)]".
12:46:36  (dependency required by "dev-lang/python-3.10.12::portage-stable" [ebuild])
12:46:36  (dependency required by "app-misc/ca-certificates-3.91::coreos" [ebuild])
12:46:36  (dependency required by "dev-libs/openssl-3.0.9::coreos" [ebuild])
12:46:36  (dependency required by "net-misc/curl-8.1.2::portage-stable" [ebuild])
12:46:36  (dependency required by "app-crypt/gnupg-2.2.35-r1::coreos" [ebuild])
12:46:36  (dependency required by "dev-vcs/git-2.39.3::portage-stable[gpg]" [ebuild])
12:46:36  (dependency required by "sys-libs/nss-usrfiles-2.30-r1::coreos" [ebuild])
12:46:36  (dependency required by "@system" [argument])
```

**Comment by krnowak** [comment]
> ```
> 12:46:36  emerge: there are no ebuilds to satisfy "dev-lang/python-exec[python_targets_python3_10(-)]".
> 12:46:36  (dependency required by "dev-lang/python-3.10.12::portage-stable" [ebuild])
> 12:46:36  (dependency required by "app-misc/ca-certificates-3.91::coreos" [ebuild])
> 12:46:36  (dependency required by "dev-libs/openssl-3.0.9::coreos" [ebuild])
> 12:46:36  (dependency required by "net-misc/curl-8.1.2::portage-stable" [ebuild])
> 12:46:36  (dependency required by "app-crypt/gnupg-2.2.35-r1::coreos" [ebuild])
> 12:46:36  (dependency required by "dev-vcs/git-2.39.3::portage-stable[gpg]" [ebuild])
> 12:46:36  (dependency required by "sys-libs/nss-usrfiles-2.30-r1::coreos" [ebuild])
> 12:46:36  (dependency required by "@system" [argument])
> ```

There are still packages that had no python 3.11 in python_compat. Those will just need an update. I think Krish already managed to do it for most of them.

**Comment by krnowak** [comment]
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/904/cldsv

**Comment by krnowak** [comment]
Fixed grub on my end and kicked off the CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/907/cldsv

**Comment by krnowak** [comment]
Needed to refresh our gentoolkit patch, CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/915/cldsv

**Comment by krnowak** [comment]
@krishjainx : Please cherry pick commits 39ddc9531290697ac338cbcde06cefc9ca28cda6 and 39ddc9531290697ac338cbcde06cefc9ca28cda6 from my krnowak/python-3.11 branch.

Changes in portage-stable packages:

--

- app-misc/pax-utils: [PROD] [DEV]
  - from 1.3.3 to 1.3.7
  - still unstable for amd64, so added accept keywords to overlay
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - dropped debug USE flag, most likely because of the build system change (switched to meson)
  - dropped now implicit kernel_linux USE flag
  - added test USE flag
  - added man USE flag (for building man pages, requires app-text/xmlto, disabled)
  - release notes: https://gitweb.gentoo.org/proj/pax-utils.git/log/?h=v1.3.7

- app-portage/gentoolkit:
  - from 0.5.1-r1 to 0.6.1-r3
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - bumped sys-apps/portage dep to require at least 3.0.32
  - replaced sys-apps/gawk dep with app-alternatives/awk
  - needed to refresh our user patch
  - release notes: https://github.com/gentoo/gentoolkit/blob/gentoolkit-0.6.1/NEWS

- dev-cpp/gtest:
  - from 1.10.0_p20200702 to 1.13.0
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - release notes: https://github.com/google/googletest/releases/tag/v1.13.0 (1.12.1 - https://github.com/google/googletest/releases/tag/release-1.12.1, 1.12.0 - https://github.com/google/googletest/releases/tag/release-1.12.0, 1.11.0 - https://github.com/google/googletest/releases/tag/release-1.11.0)

- sys-libs/ldb: [PROD] [DEV]
  - from 2.4.1-r1 to 2.4.4
  - (2.5.3 is available too, but our samba requires <2.5.0 still)
  - bumped python compat to python 3.{9..11}
  - release notes: https://gitlab.com/samba-team/samba/-/commit/b686ef00da46d4a0c0aba0c61b1866cbc9b462b6 (2.4.3 - https://gitlab.com/samba-team/samba/-/commit/604f94704f30e90ef960aa2be62a14d2e614a002, 2.4.2 - https://gitlab.com/samba-team/samba/-/commit/d93892d2e8ed69758c15ab18bc03bba09e715bc6)

- sys-libs/talloc: [PROD] [DEV]
  - from 2.3.3 to 2.4.0
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - added valgrind USE flag
  - release notes: https://gitlab.com/samba-team/samba/-/commit/5224ed98eeba43f22b5f5f87de5947fbb1c1c7c1 (2.3.4 - https://gitlab.com/samba-team/samba/-/commit/0189ccf9fc3d2a77cc83cffe180e307bcdccebb4)

- sys-libs/tdb: [PROD] [DEV]
  - from 1.4.5 to 1.4.8
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - release notes: https://gitlab.com/samba-team/samba/-/commit/eab796a4f9172e602dc262f3c99ead35b35929e7 (1.4.7 - https://gitlab.com/samba-team/samba/-/commit/27ceb1c3ad786386e746a5e2968780d791393b9e, 1.4.6 - https://gitlab.com/samba-team/samba/-/commit/1c776e54cf33b46b2ed73263f093d596a0cdbb2f)

- sys-libs/tevent: [PROD] [DEV]
  - from 0.11.0 to 0.14.1
  - EAPI 8
  - bumped python compat to python 3.{9..11}
  - new USE flag test
  - bumped dep on sys-libs/talloc to 2.4.0
  - dev-util/cmocka dep is needed only for tests
  - use bundled cmocka when we disable tests
  - release notes: https://gitlab.com/samba-team/samba/-/commit/d80f28b081e515e32a480daf80b42cf782447a9c (0.14.0 - https://gitlab.com/samba-team/samba/-/commit/3c6d28ebae27dba8e40558ae37ae8138ea0b4bdc, 0.13.0 - https://gitlab.com/samba-team/samba/-/commit/63d4db63feda920c8020f8484a8b31065b7f1380, 0.12.1 - https://gitlab.com/samba-team/samba/-/commit/53692735c733d01acbd953641f831a1f5e0cf6c5, 0.12.0 - ?)

- x11-base/xorg-proto:
  - from 2021.5 to 2023.2
  - unstable for amd64, so added accept keywords to overlay
  - EAPI 8
  - release notes: none

--

**Review by krnowak — APPROVED** [review]
CI passed, thanks.

http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/915/cldsv/

**Pull request merged**
