### PR TITLE
docker 24.0.9, runc 1.1.12 for main

### PR DESCRIPTION
**Pull request by krnowak**
- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by pothos** [comment]
Do you think the test failure is due to the update to 25.0.2?  (by the way, the PR title needs correction)
If that's the case, for a quick solution I would suggest to stick to 24.

**Comment by krnowak** [comment]
> Do you think the test failure is due to the update to 25.0.2? (by the way, the PR title needs correction) If that's the case, for a quick solution I would suggest to stick to 24.

Yep, just found out that [device-mapper storage driver was removed in v25](https://github.com/docker/cli/blob/v25.0.0/docs/deprecated.md#device-mapper-storage-driver). Will stick to v24 for now. But we will probably need to think about a possible migration path of docker storage from devicemapper to overlay2 maybe using a postinst script.

**Comment by pothos** [comment]
> > Do you think the test failure is due to the update to 25.0.2? (by the way, the PR title needs correction) If that's the case, for a quick solution I would suggest to stick to 24.
> 
> Yep, just found out that [device-mapper storage driver was removed in v25](https://github.com/docker/cli/blob/v25.0.0/docs/deprecated.md#device-mapper-storage-driver). Will stick to v24 for now. But we will probably need to think about a possible migration path of docker storage from devicemapper to overlay2 maybe using a postinst script.

Oh, yes, a similar topic was the Docker btrfs storage backend: https://www.flatcar.org/releases#release-3794.0.0

**Comment by pothos** [comment]
What was the revert commit about? I think we can drop it because the nightly would overwrite again, or?

**Review by pothos — APPROVED** [review]

**Comment by krnowak** [comment]
> What was the revert commit about? I think we can drop it because the nightly would overwrite again, or?

Ah, I'll drop it. It was there, because nightly SDK was not yet available so CI was failing. With the revert, CI pulled a day older SDK.

**Pull request merged**
