### PR TITLE
app-admin/locksmith: Stop using deprecated resource control options

### PR DESCRIPTION
**Pull request by krnowak**
Pulls in https://github.com/flatcar/locksmith/pull/20

### CODE REVIEW

**Comment by t-lo** [comment]
For some reason the build workflow now thinks that no command was issued :disappointed: 
Let's try once more:

/build-image

**Comment by krnowak** [comment]
Tests passed, ready for review.

**Review by dongsupark — APPROVED** [review]
Looks good.

Adding changelog would be great as well.

**Comment by krnowak** [comment]
Added the changelog, merging.

**Pull request merged**
