### PR TITLE
Upgrade dev-lang/rust and virtual/rust in main from 1.74.1 to 1.75.0

### PR DESCRIPTION
**Pull request by flatcar-infra**
Subject says it all.

### CODE REVIEW

**Comment by pothos** [comment]
Started a two-phase SDK build in [jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1246/cldsv/)

**Comment by pothos** [comment]
I pushed patches for build failures. They are not part of the "apply flatcar patches" commit because I expect this to be only needed until Gentoo updates to 1.75.

**Comment by pothos** [comment]
There is an alternative fix in https://github.com/rust-lang/rust/pull/119582 - will need to test if that works, too, but the current one looks good so far for our usage.

**Review by dongsupark — APPROVED** [review]
Both upstream approaches are fine.

**Pull request merged**
