### PR TITLE
oem_sysext_util: Mount overlay on top of /usr before installing sysext

### PR DESCRIPTION
**Pull request by jepio**
# Mount overlay on top of /usr before installing sysext

This fixes the issue of sysext creating running out of disk space after we changed the ext4 inode size to 256 bytes.

## How to use

```
./build_packages
./build_image
./image_to_vm.sh --format=azure
```

## Testing done

Performed the step in `how to use` - successfully.

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Review by krnowak — APPROVED** [review]
Looks good. We probably could then just use create squashfs image just from the upper dir instead of generating listings and copying this over to a separate "sysext rootfs".

**Comment by jepio** [comment]
jenkins CI is failing:
```
overlayfs: filesystem on '/home/sdk/build/images/amd64-usr/latest/oem-qemu-sysext/sysext-oem-qemu/overlay.upper' not supported as upperdir
```
not sure why. `build/images` should be a volume

**Comment by jepio** [comment]
Looks like the images directory was located in an overlayfs, i've fixed that here and rerunning jenkins: https://github.com/flatcar/scripts/pull/946/commits/6ebbe5f2b9923b59f571100d7df58492ce205359.

**Comment by krnowak** [comment]
> jenkins CI is failing:
> 
> ```
> overlayfs: filesystem on '/home/sdk/build/images/amd64-usr/latest/oem-qemu-sysext/sysext-oem-qemu/overlay.upper' not supported as upperdir
> ```
> 
> not sure why. `build/images` should be a volume/bind-mount.

Interesting, my openssh PR (which is rebased on top of this PR) went through the Jenkins build just fine.

**Comment by jepio** [comment]
@krnowak Finally have a working version, please take a look.

Proof of success here: http://192.168.42.7:8080/job/container/job/packages_all_arches/2054/cldsv/.

**Review by krnowak — APPROVED** [review]

**Pull request merged**
